name: 'artifacts_integration_tests'
version: '1.0'
config-version: 2

profile: 'dbt_artifacts'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
    +persist_docs:
      relation: true
      columns: true
seeds:
  +quote_columns: false
