version: 2

sources:
  - name: ga4
    schema: "{{ var('stg_ga4_events_export_schema') }}"

    freshness:
      warn_after: {count: 1, period: day}

    loaded_at_field: event_timestamp

    tables:
      - name: tracks
        identifier: events_*
