version: 2

sources:

  - name: custom_events
    database: "{{ var('stg_custom_events_database', target.database) }}"
    schema: "{{ var('stg_custom_events_schema', target.schema) }}"

    tables:
      - name: order_lines
        identifier: order_lines
      - name: orders
        identifier: orders
      - name: users
        identifier: users
