version: 2

sources:

  - name: custom_ltv
    database: "{{ var('stg_custom_ltv_database', target.database) }}"
    schema: "{{ var('stg_custom_ltv_schema', target.schema) }}"

    tables:
      - name: user_ltv
        identifier: customer_ltv_ndays
