version: 2

sources:

  - name: custom_currency
    database: "{{ var('stg_custom_currency_database', target.database) }}"
    schema: "{{var('stg_custom_currency_schema')}}"

    tables:
      - name: currency_rates
        identifier: currency_rates
