name: Main branch test package

# triggers for the workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # These are configured in GitHub secrets
  DBT_PROFILES_DIR: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/integration_tests
  SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
  SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
  SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
  SNOWFLAKE_TEST_ROLE: ${{ secrets.SNOWFLAKE_TEST_ROLE }}
  SNOWFLAKE_TEST_DATABASE: ${{ secrets.SNOWFLAKE_TEST_DATABASE }}
  SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_WAREHOUSE }}

jobs:
  ci-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
          architecture: 'x64'

      - name: Setup dbt
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip setuptools
          pip install dbt-snowflake --upgrade

      - name: Run Tests - Snowflake
        run: |
          . venv/bin/activate
          cd ./integration_tests
          echo $DBT_PROFILES_DIR
          dbt deps
          dbt run-operation create_artifact_resources
          dbt seed --full-refresh
          dbt run-operation upload_dbt_artifacts --args '{filenames: [manifest, run_results]}'
          dbt run --full-refresh
          dbt run
          dbt run-operation upload_dbt_artifacts --args '{filenames: [manifest, run_results]}'
          dbt test
          dbt run-operation upload_dbt_artifacts --args '{filenames: [run_results]}'
          dbt source snapshot-freshness
          dbt run-operation upload_dbt_artifacts --args '{filenames: [sources]}'
          dbt docs generate
          dbt run-operation upload_dbt_artifacts --args '{filenames: [catalog]}'
